name: Deploy to GitHub Pages

on:
  workflow_dispatch:

env:
  NODE_VERSION: 14

jobs:
  build_and_publish:
    name: Build and publish

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        fetch-depth: 0

    - name: Merge main branch
      run: |
        git config user.name auto-deploy
        git fetch
        git merge origin/main

    - name: Setup node env
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Setup codedoc
      run: |
        npm i -g @codedoc/cli

    - name: build
      run: |
        npm install
        codedoc build
  
    - name: Publish
      run: |
        git add .
        git commit -m "Auto deploy by SHA ${{ github.sha }}"
        git push
